### ISSUE TITLE
制作困难数据集的问题

### ISSUE THREAD

**Issue by CrossEntropy** [HiBugs/MTCNN#3]
Hi @HiBugs 很帮的工作，感谢你的分享!

在  `gen_hard_example` 这个文件中，为何只从 `wideface` 中选取了 3000 张图像呢? 感谢您的解答。

**Comment by HiBugs** [comment]
这个只是作为示例，你也可以设置为更多。
我这里代码写的比较粗糙，相当于先保存到内存，然后一次性写入到文件中的，所以保存多了可能会导致内存不够。

**Comment by CrossEntropy** [comment]
@HiBugs 谢谢您的解答
